swagger: "2.0" # realized based on Swagger 2.0 version
info:
  version: v1
  title: Whitelist
  description: Whitelist Related Interface
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/whiteList": #IP Whitelist of Instance
    put:
      description: Modify the IP whitelist that allows access to the instance. The whitelist is a list of IP/IP segments that are allowed to access the current instance. By default, the whitelist is open to the VPC. If the user has enabled the internet access, you need to configure a whitelist for the IP of the internet.
      operationId: modifyWhiteList
      x-jdcloud-internal: true
      parameters:
        - name: ips
          required: true
          in: query
          type: string
          description: For IP or IP segment, different IP/IP segments shall be separated by commas, for example 0.0.0.0/0,192.168.0.10
      responses:
        200:
          description: OK
    get:
      description: View the current whitelist of RDS instances. The whitelist is a list of IP/IP segments that are allowed to access the current instance. By default, the whitelist is open to the VPC. If the user has enabled the internet access, you need to configure a whitelist for the IP of the internet.
      operationId: describeWhiteList
      #x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  whiteLists:
                    type: array
                    description: Whitelist
                    items:
                      $ref: ../model/WhiteList.yaml#/definitions/WhiteList
# General Parameters for Path
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region code, with range detailed in [Regions and Availability Zone Comparison Table](../Enum-Definitions/Regions-AZ.md)
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: RDS instance ID, which uniquely identifies an RDS instance