swagger: "2.0"
info:
  version: "v1"
  title: Sensitive Operation Protection
  description: Related interfaces of sensitive operation protection (SOP)
host: "sop.jdcloud-api.com"
x-jdcloud-version: "v1"
x-jdcloud-revision: "0.1.0"
