swagger: "2.0"
definitions:
  instanceSpec:
    type: object
    x-jdcloud-module: ipanti
    properties:
      name:
        type: string
        description: "Instance Name"
      buyType:
        type: integer
        description: "Purchase Type, 1->newly purchased  3->upgraded"
      timeUnit:
        type: integer
        description: "Purchase Duration Unit, 3->month  4->year"
      timeSpan:
        type: integer
        description: "Purchase Duration"
      carrier:
        type: string
        description: "ISP Line: TELECOM->China Telecom's ISP line  UNICOM->Unicom's ISP line CMCC->CMCC's ISP line"
      bp:
        type: integer
        description: "Minimum bandwidth: unit: Gbps"
      ep:
        type: integer
        description: "Elastic bandwidth: unit: Gbps"
      bw:
        type: integer
        description: "Business bandwidth: unit: Mbps"
      returnUrl:
        type: string
        description: "The page jumped to after the payment succeeds. The field is transferred in the console interaction mode"
