swagger: "2.0"
info:
  version: "v1"
  title: Elastic Network Interface
  description: Elastic Network Interface APIs

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/networkInterfaces/":
     get:
       summary: "Query Elastic Network Interface List"
       description: "Query Elastic Network Interface List"
       operationId: describeNetworkInterfaces

       parameters:
          - name: pageNumber
            in: query
            type: integer
            default: 1
            minimum: 1
            description: Page; it is 1 by default. Value Range: [1,∞); when the pages exceed total pages, show the last page
          - name: pageSize
            in: query
            type: integer
            default: 20
            minimum: 10
            maximum: 100
            description: Paging size; it is 20 by default. Value Range: [10, 100]

          - name: filters
            in: query
            type: array
            items:
              #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
              $ref: "../../common/model/Filter.yaml#/definitions/filter"
            description: |
                   networkInterfaceIds - Elastic Network Interface ID List, Support Multiple IDs
                   networkInterfaceNames - Elastic Network Interface Name List, Support Multiple Names
                   VPCId - VPC ID of Elastic Network Interface, Support Single ID
                   subnetId	- subnet Id of Elastic Network Interface, support single Id
                   role - Network Interface Role. Value Range: Primary (primary network interface), Secondary (secondary network interface), support single role

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   networkInterfaces:
                     description: "NetworkInterface Resource Information List"
                     type: array
                     items:
                       $ref: "../model/NetworkInterface.yaml#/definitions/networkInterface"
                   totalCount:
                     description: "Total Number"
                     type: number
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: "invalid parameter"
         401:
           description: "Authentication failed"
     post:
       description: "Create network interface, can only create secondary network interface"
       operationId: CreateNetworkInterface
       parameters:
         - name: networkInterfaceSpec
           in: body
           required: true
           description: "Create Network Interface Request Parameter"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/NetworkInterfaceSpec.yaml#/definitions/networkInterfaceSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               result:
                 description: "Returned Results"
                 properties:
                   networkInterfaceId:
                     description: "Elastic Network Interface ID"
                     type: string
               requestId:
                 description: "Request ID"
                 type: string
         429:
           description: "NetworkInterface quota limit exceeded"
         404:
           description: "Resource 'subnetId' not found"
         409:
           description: "Resource 'primaryIp' already be used"

  "/networkInterfaces/{networkInterfaceId}":
      get:
        summary: "Query Elastic Network Interface Information Details"
        description: "Query Elastic Network Interface Information Details"
        operationId: describeNetworkInterface

        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Returned Results"
                  properties:
                    networkInterface:
                      description: "networkInterface Resource Information"
                      $ref: "../model/NetworkInterface.yaml#/definitions/networkInterface"
                requestId:
                  description: "Request ID"
                  type: string

          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"

      delete:
        summary: "Delete Elastic Network Interface"
        description: "Delete Elastic Network Interface APIs"
        operationId: deleteNetworkInterface
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          404:
            description: NOT_FOUND
   
      patch:
        summary: "Modify Elastic Network Interface"
        description: "Modify Elastic Network Interface APIs"
        operationId: modifyNetworkInterface
        parameters:
          - name: modifyNetworkInterfaceSpec
            in: body
            required: true
            description: "Modify Elastic Network Interface"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifyNetworkInterfaceSpec.yaml#/definitions/modifyNetworkInterfaceSpec"

        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
          404:
            description: Resource not found
           

  "/networkInterfaces/{networkInterfaceId}:associateElasticIp":
     post:
       description: "Associate Elastic IP Interface to Network Interface"
       operationId: associateElasticIp
       parameters:
         - name: associateElasticIpSpec
           in: body
           required: true
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/AssociateElasticIpSpec.yaml#/definitions/associateElasticIpSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/networkInterfaces/{networkInterfaceId}:disassociateElasticIp":
     post:
       description: "Disassociate Elastic IP Interface from Network Interface"
       operationId: disassociateElasticIp
       parameters:
         - name: disassociateElasticIpSpec
           in: body
           required: true
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/DisassociateElasticIpSpec.yaml#/definitions/disassociateElasticIpSpec"
       responses:
         200:
           description: "Successful operation"
           schema:
             type: object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/networkInterfaces/{networkInterfaceId}:assignSecondaryIps":
     post:
       description: "Assign Secondary IP Interface to Network Interface"
       operationId: assignSecondaryIps
       parameters:
         - name: assignSecondaryIpsSpec
           in: body
           required: true
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/AssignSecondaryIpsSpec.yaml#/definitions/assignSecondaryIpsSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               requestId:
                 description: "Request ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/networkInterfaces/{networkInterfaceId}:unassignSecondaryIps":
    post:
      description: "Delete Secondary IP Interface from Network Interface"
      operationId: unassignSecondaryIps
      parameters:
        - name: unassignSecondaryIpsSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/UnassignSecondaryIpsSpec.yaml#/definitions/unassignSecondaryIpsSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "Request ID"
                 type: string
        400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
        404:
           description: Resource not found



parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  networkInterfaceId:
    name: networkInterfaceId
    in: path
    required: true
    type: string
    description: networkInterface ID
