swagger: "2.0"
info:
  version: "v1"
  title: Virtual Private Cloud
  description: Virtual private cloud APIs

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/vpcs/":
     #describe vpcs
    get:
      summary: "Query virtual private cloud list"
      description: "Query virtual private cloud list"
      operationId: describeVpcs
    
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page; it is 1 by default, the value range: [1,∞); when the pages exceed total pages, show the last page"
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Paging size; it is 20 by default; value range: [10, 100]"
        - name: filters
          in: query
          type: array
          items:
            #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
                 vpcIds - vpc ID list, support multiple IDs
                 vpcNames - vpc name list, support multiple names
    
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Returned results"
                properties:
                  vpcs:
                    description: "Vpc resource information list"
                    type: array
                    items:
                      $ref: "../model/Vpc.yaml#/definitions/vpc"
                  totalCount:
                    description: "Total number"
                    type: number
              requestId:
                description: "Request ID"
                type: string
    
    post:
      summary: "Create virtual private cloud"
      description: "Create virtual private cloud"
      operationId: createVpc
      parameters:
        - name: vpcSpec
          in: body
          required: true
          description: "Apply for creating vpc request parameter"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/VpcSpec.yaml#/definitions/vpcSpec"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              result:
                 description: "Returned results"
                 properties:
                   vpcId:
                     description: "Virtual private cloud ID"
                     type: string
              requestId:
                 description: "Request ID"
                 type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        409:
          description: "Parameter conflict"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"
      

  "/vpcs/{vpcId}":
      #describe vpc
      get:
        summary: "Query Vpc information details"
        description: "Query Vpc information details"
        operationId: describeVpc
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Returned results"
                  properties:
                    vpc:
                      description: "Vpc resource information"
                      $ref: "../model/Vpc.yaml#/definitions/vpc"
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"

      patch:
        summary: "Modify virtual private cloud"
        description: "Modify virtual private cloud interface"
        operationId: modifyVpc
        x-jdcloud-internal: true
        parameters:
          - name: modifyVpcSpec
            in: body
            required: true
            description: "Modify virtual private cloud"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifyVpcSpec.yaml#/definitions/modifyVpcSpec"

        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "Invalid parameter"
          404:
            description: "Not found"
          409:
            description: "Parameter conflict" 
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"
          

      delete:
        summary: "Delete virtual private cloud"
        description: "Delete virtual private cloud"
        operationId: deleteVpc
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "Request ID"
                  type: string
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          409:
            description: "Parameter conflict" 
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  vpcId:
    name: vpcId
    in: path
    required: true
    type: string
    description: Vpc ID
