swagger: "2.0"
info:
  version: "v1"
  title: query
  description: API related to XDATA-DW query

basePath: /regions/{regionId}

paths:
  "/dwQuery:executeRasQuery":
    ###################### Execute SparkSQL ######################
        post:
          description: "Execute the Spark SQL script written by the user"
          operationId: executeRasQuery
          parameters:
            - name: databaseName
              in: query
              type: string
              required: false
              description: "Database name"
            - name: sql
              in: query
              type: string
              required: true
              description: "sql script"
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queueName
              in: query
              type: string
              required: false
              description: "Queue name"
            - name: source
              in: query
              type: string
              required: false
              description: "Resource name"
            - name: callBackURL
              in: query
              type: string
              required: false
              description: "Callback address name"
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance name"
            - name: instanceOwnerName
              in: query
              type: string
              required: false
              description: "Instance owner name"
            - name: isExplain
              in: query
              type: string
              required: false
              description: "Is interpretation required or not"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: integer
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:executePySparkQuery":
    ###################### Execute PySpark script ######################
        post:
          description: "Execute the PySpark script written by the user"
          operationId: executePySparkQuery
          parameters:
            - name: script
              in: query
              type: string
              required: true
              description: "PySpark script"
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: instanceName
              in: query
              type: string
              required: true
              description: "Instance name"
            - name: instanceOwnerName
              in: query
              type: string
              required: false
              description: "Instance owner name"
            - name: scriptType
              in: query
              type: string
              required: false
              description: "Script type name"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: integer
                  requestId:
                    type: string

  "/dwQuery:getRasQueryState":
    ###################### Obtain the search status ######################
        get:
          description: "Obtain the search status of the user’s Spark SQL script"
          operationId: getRasQueryState
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id name"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:getPySparkExecuteState":
    ###################### Obtain the PySpark script execution status ######################
        get:
          description: "Obtain the execution status of the user’s PySpark script"
          operationId: getPySparkExecuteState
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                      data:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:getRasQueryLog":
    ###################### Obtain a search log ######################
        get:
          description: "Obtain a search log of the user’s Spark SQL script"
          operationId: getRasQueryLog
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:getRasQueryResult":
    ###################### Obtain the search result ######################
        get:
          description: "Obtain the search result of the user’s Spark SQL script"
          operationId: getRasQueryResult
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:getPySparkExecuteResult":
    ###################### Obtain the PySparkExecute result ######################
        get:
          description: "Obtain the execution result of the user's PySpark script"
          operationId: getPySparkExecuteResult
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:cancelRasQuery":
    ###################### Terminate the search ######################
        post:
          description: "Terminate the search on the user's Spark SQL script"
          operationId: cancelRasQuery
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

  "/dwQuery:cancelPySparkQuery":
    ###################### Terminate a PySpark task ######################
        post:
          description: "Terminate a user's PySpark script task"
          operationId: cancelPySparkJob
          parameters:
            - name: userName
              in: query
              type: string
              required: true
              description: "User name"
            - name: queryId
              in: query
              type: string
              required: true
              description: "Search an id"
          responses:
            200:
              description: OK
              schema:
                properties:
                  result:
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  requestId:
                    type: string
            500:
              description: "Internal server error"

# Path general parameter
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID