swagger: "2.0"
info:
  version: "v1"
  title: JDCLOUD streaming data bus API
  description: Provide related APIs for streaming data bus topic.
host: "streambus.jdcloud-api.com"
x-jdcloud-version: "v1"
x-jdcloud-revision: "1.0.1"
