swagger: "2.0"
info:
  description: Cloud Monitor APIs, mainly comprising create, read, update, delete of monitoring rules and query of monitoring item data
  title: Cloud Monitor
  version: "v1"
host: monitor.jdcloud-api.com
x-jdcloud-version: v1
x-jdcloud-revision: "1.1.1"