swagger: "2.0"
definitions:
  ipResource:
    type: object
    x-jdcloud-module: baseanti
    properties:
      ip:
        type: string
        description: EIP address
      bandwidth:
        type: integer
        description: Bandwidth cap, unit: Mbps
      safeStatus:
        type: integer
        description: Security status, 0->safe  1->clean  2->black hole