swagger: "2.0"
definitions:
  getSecurityTokenInfo:
    x-jdcloud-module: sop
    required:
      - type
      - code
      - action
    properties:
      type:
        type: integer
        description: Verification methods of operation protection: 1-SMS, 2-email, 3-MFA
      code:
        type: string
        description: Verification code
      action:
        type: string
        description: Action action serviceName:actionName
      durationSeconds:
        type: integer
        description: The unit of token validity period is second; verification in OpenAPI third-party MFA method is valid; the default token validity period of SMS and email is 300 seconds, and the validity period of MFA is 30 seconds
