swagger: "2.0"
definitions:
  verificationCodeInfo:
    x-jdcloud-module: sop
    required:
      - action
      - type
    properties:
      action:
        type: string
        description: "Action action serviceName:actionName"
      type:
        type: integer
        description: "dcd verification methods: mobile-1  email-2"