swagger: "2.0"
info:
  version: "v1"
  title: Resolution Record
  description: Cloud resolution OpenAPI resolution record API

basePath: /regions/{regionId}

paths:          
  /domain/{domainId}/RR:
  ###################### Query Resolution Record of Main Domain Name ######################
    get:
      description: "Query the resolution record of the main domain name"
      operationId: searchRR
      parameters:
        - name: pageNumber
          in: query
          type: integer
          description: Current page, starting value of 1, default value of 1
          required: false
        - name: pageSize
          in: query
          type: integer
          description: Number of rows per page set during the page query, default value of 10
          required: false
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    description: List of the resolution record
                    type: array
                    items:
                      $ref: "../model/RR.yaml#/definitions/RR"
                  totalCount:
                    description: Number of all resolution records
                    type: integer
                  totalPage:
                    description: Pages of all resolution records
                    type: integer
                  currentCount:
                    description: Resolution records of current page
                    type: integer
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/viewTree:
  ###################### Query All DNS Resolution Lines ######################
    get:
      description: "Query all basic cloud resolution lines"
      operationId: getViewTree
      parameters:
        - name: loadMode
          in: query
          type: integer
          required: false
          description: Display Mode
        - name: packId
          in: query
          type: integer
          required: true
          description: Package ID
        - name: viewId
          in: query
          type: integer
          required: true
          description: view ID, 0 in default
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    description: Tree of the resolution line
                    type: array
                    items:
                      $ref: "../model/RR.yaml#/definitions/viewTree"
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RRAdd:
  ###################### Add Resolution Record of Domain Name ######################
    post:
      description: "Add a resolution record of the domain name"
      operationId: addRR
      parameters:
        - name: req
          in: body
          description: RR Parameter
          required: true
          schema:
            $ref: "../model/RR.yaml#/definitions/addRR"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  dataList:
                    description: Resolution record result after successful addition
                    $ref: "../model/RR.yaml#/definitions/RR"
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RRUpdate:
  ###################### Modify Resolution Record of Domain Name ######################
    post:
      description: "Modify a resolution record of the main domain name"
      operationId: updateRR
      parameters:
        - name: req
          in: body
          schema:
            $ref: "../model/RR.yaml#/definitions/updateRR"
          required: true
          description: UpdateRR Parameter
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: ID of this request
                type: string
        400:
          description: BAD_REQUEST
          
  /domain/{domainId}/RROperate:
  ###################### Operation Set of Domain Name Resolution Record ######################
    post:
      description: "Enable, disable, delete the resolution records under the main domain name"
      operationId: operateRR
      parameters:
        - name: ids
          in: query
          type: array
          items:
            type: integer
          required: true
          description: Resolution record ID of the operation demanded
        - name: action
          in: query
          type: string
          required: true
          description: Operation type, on->enable, off->disable, del->delete
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST 
         
# General Parameters for Path
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID to which the instance belongs
  domainId:
    name: domainId
    in: path
    required: true
    type: string
    description: Domain Name ID