swagger: "2.0"
info:
  version: "v1"
  title: Website Monitoring
  description: Cloud resolution OpenAPI website monitoring API

basePath: /regions/{regionId}

paths:
  /domain/{domainId}/monitor:
  ###################### View Monitoring Items of the Main Domain ######################
    get:
      description: "View the configuration and status of the monitoring items of the main domain"
      operationId: getMonitor
      parameters:
        - name: pageIndex
          in: query
          type: integer
          required: false
          description: Current page, starting value of 1, default value of 1
        - name: pageSize
          in: query
          type: integer
          required: false
          description: Number of rows per page set during paged query
        - name: searchValue
          in: query
          type: string
          required: false
          description: Query Value
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  currentCount:
                    type: integer
                    description: Number of monitoring items of current website page
                  totalCount:
                    type: integer
                    description: Number of monitoring items of all websites
                  totalPage:
                    type: integer
                    description: Pages for all website monitoring items
                  dataList:
                    description: list of website monitoring items of the current page
                    type: array
                    items:
                      $ref: "../model/Monitor.yaml#/definitions/monitor"
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
  /domain/{domainId}/monitorAdd:
  ###################### Add Domain Name Monitoring Items (set by default) ######################
    post:
      description: "Add monitoring items for subdomains, by default, all monitoring items of subdomains are added to the monitoring"
      operationId: addMonitor
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: Subdomain
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST  
          
  /domain/{domainId}/getTargets:
  ###################### Query Available Monitoring Objects of Subdomain ######################
    get:
      description: "Query available monitor objects of subdomains"
      operationId: getTargets
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: Subdomain
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    description: Array of available monitoring objects returned
                    type: array
                    items:
                      type: string  
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST  
  
  /domain/{domainId}/monitorAddTarget:
  ###################### Add Monitoring Items of Subdomain ######################
    post:
      description: "Add certain monitoring objects as the monitoring items for the subdomains"
      operationId: addMonitorTarget
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: Subdomain
        - name: targets
          description: Array of available monitoring objects of subdomain         
          in: query
          required: true 
          type: array
          items:
            type: string
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST 
          
  /domain/{domainId}/monitorOperate:
  ###################### Monitoring Items Operation (including: delete, pause, start, manual recovery, manual switch) ######################
    post:
      description: "Operation collection for monitoring items, including: delete, pause, start, manual recovery and manual switch"
      operationId: operateMonitor
      parameters:
        - name: action
          in: query
          type: string
          required: true
          description: Delete - del, pause - stop, start - start, manually recover - recover, manually switch - switch
        - name: ids
          in: query
          type: array
          items:
            type: integer
          required: true
          description: Monitor Item ID
        - name: switchTarget
          in: query
          type: string
          required: false
          description: Machine value of the monitoring items, required for manual switch
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
  /domain/{domainId}/monitorUpdate:
  ###################### Modification of Domain Monitoring Items  ######################
    post:
      description: "Modification of domain name monitoring items"
      operationId: updateMonitor
      parameters:
        - name: updateMonitor
          description: Monitoring Item Information Setting
          in: body
          required: true
          schema:
            $ref: "../model/Monitor.yaml#/definitions/updateMonitor"       
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
                 
  /domain/{domainId}/monitor/alarminfo:
  ###################### Alarm Information for Monitoring Items of Main Domain ######################
    get:
      description: "Alarm information for monitoring items of the main domain"
      operationId: getMonitorAlarmInfo
      parameters:
        - name: pageIndex
          in: query
          type: integer
          required: false
          description: Current page, starting value of 1, default value of 1
        - name: pageSize
          in: query
          type: integer
          required: false
          description: Number of rows per page set during paged query
        - name: searchValue
          in: query
          type: string
          required: false
          description: Keyword
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  currentCount:
                    type: integer
                    description: Number of alarm information of current page
                  totalCount:
                    type: integer
                    description: Number of all alarm information
                  totalPage:
                    type: integer
                    description: Pages of all alarm information
                  dataList:
                    type: array
                    description: Array of alarm information of the current page
                    items:
                      $ref: "../model/Monitor.yaml#/definitions/monitorAlarmInfo"
              requestId:
                type: string
                description: ID of this request
        400:
          description: BAD_REQUEST
# General Parameters for Path
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID to which the instance belongs
  domainId:
    name: domainId
    in: path
    required: true
    type: string
    description: Domain Name ID