swagger: "2.0"
definitions:
  filter:
    x-jdcloud-module: common
    type: object
    required:
      - name
      - values
    properties:
      name:
        type: string
        description: Name of filter requirements
      operator:
        type: string
        description: Operator of filter requirements is eq by default
        enum:
          - eq
          - lt
          - le
          - gt
          - ge
          - ne
          - in
          - like
      values:
        type: array
        description: Value of filter requirements
        items:
          type: string

