swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: common
    type: object
    properties:
      name:
        type: string
        description: Name of the quota item
      max:
        type: integer
        description: Quota
      used:
        type: integer
        description: Number used