swagger: "2.0"
info:
  version: "v1"
  title: CDS APIs
  description: CDS APIs, provides functions including creating cloud disk services in batches, querying a cloud disk service, deleting a cloud disk service, expanding a cloud disk service, modifying the cloud disk service information, and using a snapshot to restore a cloud disk service.

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/disks":
    ###################### API for Cloud Disk Service Creation ######################
    post:
      description: |
        -   Create one or more cloud disk services that are paid by configuration or by service time.
        -   Disk type includes Premium Hdd Cloud Disk and SSD Cloud Disk.
        -   The billing method defaults to paying by configuration.
        -   After creation is completed, the cloud disk service is in available status.
        -   The optional parameter snapshot ID is used to create a new disk.
        -   When creating in batches, the name of the cloud disk service is: hard disk name -number, such as myDisk-1 and myDisk-2.
        -   maxCount is the maximum effort, and it is not guaranteed that maxCount can be reached.
      summary: "Create cloud disk service"
      operationId: createDisks
      parameters:
        - name: DiskSpec
          in: body
          required: true
          description: "Create specification of the cloud disk service"
          schema:
            $ref: "../model/DiskSpec.yaml#/definitions/diskSpec"
        - name: maxCount
          in: query
          type: integer
          required: true
          description: "Instance purchase quantity; value range: [1,100]"
        - name: clientToken
          in: query
          type: string
          required: true
          description: " Idempotence check parameter"
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "Result Set"
                properties:
                  diskIds:
                    type: array
                    description: "List of cloud disk service IDs created"
                    items:
                      type: string
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### API for Cloud Disk Service List Query ######################
    get:
      operationId: describeDisks
      summary: "Query cloud disk service list"
      description: |
        -   filters, between multiple filter conditions is logic AND, and multiple values ​​inside each condition is logic OR
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "Page number, defaults is 1; value range: [1, ∞)"
          
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "Page size, default is 20; value range: [10,100]"
          
        - name: tags
          in: query
          description: Tag filter condition
          type: array
          items:
            $ref: "../model/TagFilter.yaml#/definitions/tagFilter"

        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            diskId - cloud disk service ID, accurate match, support multiple
            diskType - type of cloud disk service, accurate match, support multiple, ssd or premium-hdd
            instanceId - ID of the machine, to which the cloud disk service is attached, accurate match, support multiple
            instanceType - Type of the machine, to which the cloud disk service is attached, accurate match, support multiple
            status - availability zone, accurate match, support multiple
            az - status of cloud disk service, accurate match, support multiple
            name - name of cloud disk service, fuzzy match, support single
            multiAttach - whether the cloud disk service is multi-point attached, accurate match, support single
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                type: object
                description: "Query Result Set"
                properties:
                  disks:
                    type: array
                    description: "List of cloud disk service information details queried"
                    items:
                      $ref: "../model/Disk.yaml#/definitions/disk"
                  totalCount:
                    type: integer
                    description: "Number of cloud disk services queried"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### API for Cloud Disk Service Details Query ######################
  "/disks/{diskId}":
      get:
        summary: "Query details of a cloud disk service"
        description: "Query details of a cloud disk service"
        operationId: describeDisk
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "Query cloud disk service information details"
                  properties:
                    disk:
                      $ref: "../model/Disk.yaml#/definitions/disk"
                requestId:
                  type: string
                  description: "Request ID"
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Single Cloud Disk Service Deletion ######################
      delete:
        summary: "Delete a single cloud disk service"
        description: |
          -   delete a cloud disk service billing by configuration. The disk types include the Premium Hdd Cloud Disk and the SSD Cloud Disk.
          -   After the hard disk is deleted, the cloud disk snapshot can be retained.
          -   When the disk is released, the state of the cloud disk is to-be-attached (Available).
          -   If the disk of the specified ID does not exist, the request will be ignored.
        operationId: deleteDisk
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Cloud Disk Service Properties Modification ######################
      patch:
        summary: "Modify cloud disk service properties"
        description: "Modify the name or description of the cloud disk service, specify either"
        operationId: modifyDiskAttribute
        parameters:
          - name: name
            in: query
            type: string
            description: "Name of the cloud disk service. Only Chinese, numbers, uppercase and lowercase letters, English underline "_" and line-through "-" are allowed. It is not allowed to be blank and shall not exceed 32 characters."
          - name: description
            in: query
            type: string
            description: "Description of the cloud disk service. It allows you to enter all characters under UTF-8 encoding, but no more than 256 characters."
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for Cloud Disk Service Recovery from Snapshot ######################
  "/disks/{diskId}:restore":
      post:
        summary: "Recovering a cloud disk service from a snapshot"
        description: |
          -   Data recovery operations can only be executed on the source hard disk, from which the snapshot was taken.
          -   Snapshots can be used for data recovery operations only if the source hard disk is available.
          -   After the cloud disk service is restored, the current data will be cleared. Please be cautious.
        operationId: restoreDisk
        parameters:
          - name: snapshotId
            in: query
            type: string
            required: true
            description: "Snapshot ID used to recover the cloud disk"
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

    ###################### API for  Capacity Expansion of Cloud Disk Service ######################
  "/disks/{diskId}:extend":
      post:
        summary: "Cloud disk service capacity can only be expanded, and cannot be reduced."
        description: |
          -   Expansion of the cloud disk service requires it in available status.
          -   Capacity expansion is not allowed while the disk is creating a snapshot.
        operationId: extendDisk
        parameters:
          - name: diskSizeGB
            in: query
            type: integer
            required: true
            description: "The size of the cloud disk service after expansion is in GiB"
        responses:
          200:
            description: OK
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  diskId:
    name: diskId
    in: path
    required: true
    type: string
    description: Cloud Disk Service ID
