swagger: "2.0"
info:
  version: "v1"
  title: Sold-out APIs
  description: Check the sold-out information 

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/soldout":
   ###################### API for Sold-out Information Query  ######################
    get:
      operationId: describeSoldout
      summary: "Query cloud disk service sold-out list"
      description: "Query cloud disk service sold-out list"
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                type: object
                description: "Query Result Set"
                properties:
                  soldout:
                    type: array
                    description: "List of sold-out details queried"
                    items:
                      $ref: "../model/Soldout.yaml#/definitions/soldout"
                  totalCount:
                    type: integer
                    description: "Number of sold-out information queried in the availability zones"
              requestId:
                type: string
                description: "Request ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID

