swagger: "2.0"
definitions:
  createElasticIpSpec:
    x-jdcloud-module: vpc
    required:
      - maxCount
      - elasticIpSpec
    properties:
      maxCount:
        type: integer
        description: "Purchase number of elastic ip; value range: [1,100]"
      elasticIpAddress:
        type: string
        description: Create by assigning elastic ip address, when multiple elastic ips are applied for creation, it must be blank
      elasticIpSpec:
        $ref: "./ElasticIpSpec.yaml#/definitions/elasticIpSpec"
        description: Elastic ip specification
