swagger: "2.0"
definitions:
  modifyQuotaSpec:
    x-jdcloud-module: vpc
    required:
      - type
      - maxLimit
    properties:
      type:
        type: string
        description: "Resource type, value range: vpc, elastic_ip, subnet, security_group, vpcpeering, network_interface (quota only sums up secondary network interface)"
      parentResourceId:
        type: string
        description: If the type is vpc, elastic_ip, network_interface, do not set; if the type is subnet, security_group, vpcpeering, set as vpcId
      maxLimit:
        type: integer
        description: Quota size
