swagger: "2.0"
definitions:
  modifyNetworkSecurityGroupSpec:
    x-jdcloud-module: vpc
    properties:
      networkSecurityGroupName:
        type: string
        description: Security group name. Value range of name: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter
      description:
        type: string
        description: Security group description, value range: 0-256 of all characters entered under UTF-8 coding
