swagger: "2.0"
definitions:
  modifyVpcSpec:
    x-jdcloud-module: vpc
    properties:
      vpcName:
        type: string
        description: "VPC name, only allowed to enter Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters."
      description: "type: string"
        description: "VPC description, all characters allowed to enter under UTF-8 coding, which is not exceed 256 characters."


