swagger: "2.0"
definitions:
  modifyElasticIpSpec:
    x-jdcloud-module: vpc
    required:
      - bandwidthMbps
    properties:
      bandwidthMbps:
        type: integer
        description: "Elastic IP speed limit (unit: Mbps), value range is [1-200]"

