swagger: "2.0"
definitions:
  modifyVpcPeeringSpec:
    x-jdcloud-module: vpc
    properties:
      vpcPeeringName:
        type: string
        description: "VpcPeering name, must provide a name. Value range of name: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter"
      description:
        type: string
        description: "VpcPeering description, value range: 0-256 Chinese, English capital and lowercase letters, numbers and underline delimiter"
