swagger: "2.0"
definitions:
  networkAcl:
    x-jdcloud-module: vpc
    properties:
      networkAclId:
        type: string
        description: networkAcl ID
      networkAclName:
        type: string
        description: networkAcl name
      vpcId:
        type: string
        description: Virtual private cloud ID
      networkAclRules:
        type: array
        description: networkAcl rule list
        items:
          $ref: "./NetworkAclRule.yaml#/definitions/networkAclRule"
      subnetIds:
        type: array
        items:
          type: string
        description: networkAcl associated subnet list
      description:
        type: string
        description: "Description, all characters allowed to enter under UTF-8 coding, which is not exceed 256 characters"
      createdTime:
        type: string
        description: networkAcl creation time