swagger: "2.0"
definitions:
  routeTable:
    x-jdcloud-module: vpc

    properties:
      routeTableId:
        type: string
        description: Route table ID
      routeTableName:
        type: string
        description: Route table name, only allowed to enter Chinese, numbers, capital and lowercase letters, English underline “_” and line-through “-”, must provide a name which cannot exceed 32 characters.
      routeTableType:
        type: string
        description: Route table type, default: default route table, custom: customized route table
      description:
        type: string
        description: Route table description information, all characters allowed to enter under UTF-8 coding, which is not exceed 256 characters.
      vpcId:
        type: string
        description: Virtual private cloud ID
      routeTableRules:
        type: array
        items:
         $ref: "./RouteTableRule.yaml#/definitions/routeTableRule"
        description: Route table rule information
      subnetIds:
        type: array
        items:
          type: string
        description: Route table associated subnet list
      createdTime:
        type: string
        description: Creation time of route table

