swagger: "2.0"
definitions:
  vpcPeering:
    x-jdcloud-module: vpc
    properties:
      vpcPeeringId:
        type: string
        description: VpcPeering Id
      vpcPeeringName:
        type: string
        description: VpcPeering name, a name cannot be duplicate under the same account, value range: 1-32 Chinese, English capital and lowercase letters, numbers and underline delimiter
      vpcPeeringState:
        type: string
        description: Status, values include Connected, Disconnected, Initiated
      description:
        type: string
        description: VpcPeering description, can be null value, value range: 0-256 Chinese, English capital and lowercase letters, numbers and underline delimiter
      vpcInfo:
        $ref: "./VpcPeeringVpcInfo.yaml#/definitions/vpcPeeringVpcInfo"
        description: Vpc information launching VpcPeering
      remoteVpcInfo:
        $ref: "./VpcPeeringVpcInfo.yaml#/definitions/vpcPeeringVpcInfo"
        description: Opposite terminal Vpc information
      createdTime:
        type: string
        description: VpcPeering creation time

