swagger: "2.0"
info:
  version: "v1"
  title: Redis Order Interface
  description: Redis Order Related Interface

basePath: /regions/{regionId}

paths:
  "/orderStatus/{orderRequest}":
    ###################### Query Order Status ######################
    get:
      description: "Query Order Status"
      operationId: describeOrderStatus
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  orderStatus:
                    $ref: "../model/OrderStatus.yaml#/definitions/orderStatus"
              requestId:
                type: string

    

# General Parameters for Path
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: The Region ID of the region where the Redis instance is located. At present, the Redis has North China, South China, and East China regions, and the corresponding Region IDs are cn-north-1, cn-south-1, and cn-east-2
  orderRequest:
    name: orderRequest
    in: path
    required: true
    type: string
    description: Request requestId
