swagger: "2.0"
info:
  version: "v1"
  title: Redis Quota APIs
  description: Redis Quota Related Interface

basePath: /regions/{regionId}

paths:
  "/quota":
    ###################### Query quota information ######################
    get:
      description: "Query Account Quota Information"
      operationId: describeUserQuota
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quota:
                    $ref: "../../common/model/Quota.yaml#/definitions/quota"
              requestId:
                type: string

    ###################### Modify Quota ######################
    patch:
      description: "Modify Account Quota"
      operationId: modifyUserQuota
      x-jdcloud-internal: true
      parameters:
        - name: used
          in: query
          required: true
          type: integer
          description: Used Quota of Account
        - name: quota
          in: query
          required: true
          type: integer
          description: Upper Limit of Account Quota
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string

# General Parameters for Path
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: The Region ID of the region where the Redis instance is located. At present, the Redis has North China, South China, and East China regions, and the corresponding Region IDs are cn-north-1, cn-south-1, and cn-east-2
