swagger: "2.0"
definitions:
  topicListInfo:
    x-jdcloud-module: streambus
    title: topicListInfo
    type: object
    properties:
      archived: 
        type: integer
        description: "Whether to archive or not (0: not archived, 1: archived)"
      createdTime:
        type: string
        format: date
        description: "Time stamp of creating topic" 
      deleted:
        type: integer
        description: "Whether the topic has been deleted (0: not deleted, 1: deleted)"
      id:
        type: integer
        description: "id value of topic"
      lifecycle:
        type: integer
        description: "Reserve time after writing data"
      name:
        type: string
        description: "topic name in the streaming data bus"
      partitionNum:
        type: string
        description: "partition number in the corresponding kafka"
      remark:
        type: string
        description: "Note"
      shardNum:
        type: string
        description: "shard number in the streaming data bus"
      status:
        type: integer
        description: "0: created, 1: pending"
      topicName:
        type: string
        description: "topic name in the corresponding kafka"
      uid:
        type: string
        description: "uid in the corresponding kafka"
      updatedTime:
        type: string
        format: date
        description: "Time stamp of updating topic" 
      userPin:
        type: string
        description: "userPin of the user"
      dataSize:
        type: string
      