swagger: "2.0"
definitions:
  CcIpLimitSpec:
    type: object
    x-jdcloud-module: ipanti
    properties:
      ccSpeedLimit:
        type: integer
        description: Speed limit of each CC defense IP
      ccSpeedPeriod:
        type: integer
        description: Speed limit statistic period of each CC defense IP