swagger: "2.0"
definitions:
  metric:
    x-jdcloud-module: monitor
    type: object
    properties:
      calculateUnit:
        type: string
        description: Computing unit of indicator, such as bit/s, %, k
      metric:
        type: string
        description: English identifier of monitoring item
      metricName:
        type: string
        description: Name of monitoring item