swagger: "2.0"
definitions:
  metricDetail:
    x-jdcloud-module: monitor
    type: object
    title: MetricDetail
    properties:
      calculateUnit:
        type: string
        description: Computing unit of indicator, such as bit/s, %, byte
      metric:
        type: string
        description: English identifier of monitoring indicator
      metricName:
        type: string
        description: Name of monitoring indicator
      serviceCode:
        type: string
        description: Identifier of resource type
      downSample:
        description: Sampling frequency
        type: string

  ServiceCodeMetrics:
    x-jdcloud-module: monitor  
    type: object
    properties:
      metrics:
        type: array
        items:
          $ref: '#/definitions/metricDetail'
      serviceCode:
        type: string
        x-go-name: ServiceCode