swagger: "2.0"                                  # Implementation Based on Swagger 2.0 Version
info:
  version: "v1"                                 # OpenApi Version number
  title: Data Compute API
  description: "Data Compute APIs"
host: "xdata.jdcloud-api.com"                   # Use business line name as the secondary domain name
x-jdcloud-version: "v1"
x-jdcloud-revision: 1.0.0  #It is required to be consistent with ChangeLog
