swagger: "2.0"
definitions:
  RR:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      id:
        type: integer
        description: Unique ID of the domain name resolution
      hostRecord:
        type: string
        description: Machine Record
      hostValue:
        type: string
        description: Value of the resolution record
      jcloudRes:
        type: boolean
        description: JD Cloud Resource?
      mxPriority:
        type: integer
        description: Priority, only exists in some resolution record types
      port:
        type: integer
        description: port, only exists in some resolution record types
      ttl:
        type: integer
        description: Life time of the resolution record
      type:
        type: string
        description: Type of the resolution record
      weight:
        type: integer
        description: Weight of the resolution record              
      viewValue:
        type: array
        items:
            type: integer
        description: ID of the resolution line
  updateRR:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      domainName:
        type: string
        required: true
        description: Main Domain Name
      id:
        type: integer
        required: true
        description: Unique ID of the domain name resolution
      hostRecord:
        type: string
        required: true
        description: Machine Record
      hostValue:
        type: string
        required: true
        description: Value of the resolution record
      jcloudRes:
        type: boolean
        required: true
        description: JD Cloud Resource?  
      mxPriority:
        type: integer
        required: true
        description: Priority, only exists in some resolution record types
      port:
        type: integer
        required: true
        description: port, only exists in some resolution record types
      ttl:
        type: integer
        required: true
        description: Life time of the resolution record
      type:
        type: string
        required: true
        description: Resolution Type
      weight:
        type: integer
        required: true
        description: Weight of the resolution record              
      viewValue:
        type: integer
        required: true
        description: ID of the resolution line
  addRR:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      hostRecord:
        type: string
        description: Machine Record
        required: true
      hostValue:
        type: string
        description: Value of the resolution record
        required: true
      jcloudRes:
        type: boolean
        description: JD Cloud Resource?
        required: true        
      mxPriority:
        type: integer
        description: Priority, only exists in some resolution record types
        required: true
      port:
        type: integer
        description: port, only exists in some resolution record types
        required: true
      ttl:
        type: integer
        description: Life time of the resolution record
        required: true
      type:
        type: string
        description: Resolution Type
        required: true
      weight:
        type: integer
        description: Weight of the resolution record
        required: true        
      viewValue:
        type: integer
        description: ID of the resolution line
        required: true        
  viewTree:
    type: object
    x-jdcloud-module: clouddnsservice
    properties:
      disabled:
        type: boolean
        description: Whether this resolution line is disabled
      label:
        type: string
        description: Name of the resolution line
      leaf:
        type: boolean
        description: Whether the data is a leaf node
      value:
        type: integer
        description: Resolution Line ID
      children:
        type: array
        required: false
        items:
          $ref: "./RR.yaml#/definitions/viewTree"  
        