swagger: "2.0"
definitions:
  container:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: container
    properties:
      containerId:
        type: string  
        description: Container ID 
      status:
        type: string  
        description: Container status 
      instanceType:
        type: string  
        description: Instance type family 
      az:
        type: string  
        description: Availability zone 
      name:
        type: string  
        description: Container name 
      hostAliases:
        type: array
        items:
          $ref: "./HostAlias.yaml#/definitions/hostAlias"  
        description: Domain and IP mapping information 
      hostname:
        type: string  
        description: Machine name 
      command:
        type: array
        items: 
          type: string 
        description:  Container execution command 
      args:
        type: array
        items: 
          type: string
        description: Parameters for command execution by container 
      envs:
        type: array
        items:
          $ref: "./EnvVar.yaml#/definitions/envVar"
        description: Environment variable for execution by dynamically-assigned container 
      image:
        type: string  
        description: Image name 
      secret:
        type: string  
        description: Name cited by secret 
      tty:
        type: boolean  
        description: If a container is assigned with tty 
      workingDir:
        type: string  
        description: Container’s working catalog 
      rootVolume:
        $ref: "./VolumeMount.yaml#/definitions/volumeMount"
        description: Root Volume information 
      dataVolumes:
        type: array
        items:
          $ref: "./VolumeMount.yaml#/definitions/volumeMount"  
        description: Mounted data Volume information 
      vpcId:
        type: string  
        description: ID of primary network interface’s VPC 
      subnetId:
        type: string  
        description: ID of primary network interface’s subnet 
      privateIpAddress:
        type: string  
        description: Primary IP address of primary network interface 
      elasticIpId:
        type: string  
        description: Elastic IP ID associated to primary IP of primary network interface 
      elasticIpAddress:
        type: string  
        description: Elastic IP address associated to primary IP of primary network interface 
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: Primary network interface information 
      secondaryNetworkInterfaces:
        type: array
        items:
          $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: Elastic network interface information 
      logConfiguration:
        $ref: "./LogConfiguration.yaml#/definitions/logConfiguration" 
        description: Container log configuration information 
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: Billing configuration information 
      launchTime:
        type: string  
        description: Creation time 
      reason:
        type: string  
        description: Container termination reason 
      description:
        type: string  
        description: Container description 