swagger: "2.0"
definitions:
  instanceCloudDisk:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: Describe a disk
    properties:
        diskId:
          type: string
          description: Cloud disk service ID
        az:
          type: string
          description: Corresponding AZ
        name:
          type: string
          description: Disk name
        description:
          type: string
          description: Disk description
        diskType:
          type: string
          description: Disk type, value ssd or premium-hdd
        diskSize:
          type: integer
          description: Disk size (GiB)
        status:
          type: string
          description: "Cloud disk service type, value: creating, available, in-use, extending, restoring, deleting, deleted, error_creating, error_deleting, error_restoring or error_extending"
        createTime:
          type: string
          description: Creation time