swagger: "2.0"
definitions:
  networkInterfaceSpec:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: "Create Network Interface Request Template"
    required:
      - subnetId
      - az
    properties:
      subnetId:
        type: string  
        description: "Subnet ID"
      az:
        type: string  
        description: "Availability Zone, User’s Default Availability Zone"
      primaryIpAddress:
        type: string  
        description: "Primary IP of Network Interface"
      secondaryIpAddresses:
        type: array
        items: 
          type: string
        description: "SecondaryIp List"
      secondaryIpCount:
        type: integer     
        description: "Amount of SecondaryIp Assigned Automatically"
      securityGroups:
        type: array
        items:
          type: string
        description: "Security Group ID List "
      sanityCheck:
        type: boolean    
        description: "PortSecurity, with value 0 or 1 and default value 1"
      description: 
        type: string
        description: "Description "