swagger: "2.0"
definitions:
  secret:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: Confidential data
    properties:
      name:
        type: string
        description: Confidential data name
      type:
        type: string
        description: "Now, only the following private data type is supported: docker-registry, which is the docker registry verification type."
      createdAt:
        type: string
        description: Creation time
      data:
        $ref: "./DockerRegistryData.yaml#/definitions/dockerRegistryData"
        description: Confidential data