swagger: "2.0"
info:
  version: "v1"
  title: SMS Outgoing APIs
  description: SMS Outgoing APIs


paths:
  "/sms:sendSingleSmsMessage":
    ###################### Send a single SMS ######################
    post:
      description: "Send a single SMS"
      operationId: sendSingleSmsMessage
      x-jdcloud-internal: true
      parameters:
        - name: sendSingleMsgReqVo
          in: body
          description: Information of a single SMS
          required: true
          schema:
            $ref: "../model/SendSingleMsg.yaml#/definitions/sendSingleMsg"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string

  "/sms:sendBatchSmsMessage":
    ###################### Send SMSs in batches ######################
    post:
      description: "Send SMSs in batches"
      operationId: sendBatchSmsMessage
      x-jdcloud-internal: true
      parameters:
        - name: sendBatchMsgReqVo
          in: body
          description: SMS information in batches
          required: true
          schema:
            $ref: "../model/SendBatchMsg.yaml#/definitions/sendBatchMsg"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  successMap:
                    type: object
                    description: Successful result
                  failedMap:
                    type: object
                    description: Failed result
              requestId:
                type: string

  "/sms:sendOutSiteNotice":
      ###################### Off-site message APIs ######################
      post:
        description: "Off-site Message APIs"
        operationId: sendOutSiteNotice
        x-jdcloud-internal: true
        parameters:
          - name: sendOutSiteNoticeReqVo
            in: body
            description: Off-site Message APIs
            required: true
            schema:
              $ref: "../model/SendOutSiteNotice.yaml#/definitions/sendOutSiteNotice"
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                result:
                  properties:
                    data:
                      type: boolean
                      description: Send result information
                requestId:
                  type: string
                
  "/sms:asyncSendEmailSms":
     ###################### Asynchronous transmission of an assigned message recipient ######################
     post:
       description: "Asynchronous transmission of an assigned message recipient"
       operationId: asyncSendEmailSms
       x-jdcloud-internal: true
       parameters:
         - name: emailSmsInfoReqVo
           in: body
           description: Asynchronous transmission of an assigned message recipient
           required: true
           schema:
             $ref: "../model/EmailSmsInfo.yaml#/definitions/emailSmsInfo"
       responses:
         200:
           description: OK
           schema:
             type: object
             properties:
               result:
                 properties:
                   data:
                     type: boolean
                     description: Send result information
               requestId:
                 type: string

  "/sms:sendWithoutLimit":
     ###################### Synchronous transmission interface of an assigned message recipient ######################
     post:
       description: "Synchronous transmission interface of an assigned message recipient"
       operationId: sendWithoutLimit
       x-jdcloud-internal: true
       parameters:
         - name: emailSmsInfoReqVo
           in: body
           description: Synchronous transmission of an assigned message recipient
           required: true
           schema:
             $ref: "../model/EmailSmsInfo.yaml#/definitions/emailSmsInfo"
       responses:
         200:
           description: OK
           schema:
             type: object
             properties:
               result:
                 properties:
                   data:
                     type: boolean
                     description: Send result information
               requestId:
                 type: string

# Path general parameter
parameters:
  accessKey:
    name: accessKey
    in: path
    required: true
    type: string
    description: accessKey