swagger: "2.0"
definitions:
  permission:
    x-jdcloud-module: iam
    properties:
      id:
        type: integer
        description: Permission id error
      account:
        type: string
        description: Primary account pin
      name:
        type: string
        description: Permission name
      description:
        type: string
        description: Description
      permissionType:
        type: string
        description: Permission type
      version:
        type: string
        description: Permission revision number
      content:
        type: string
        description: Permission content
      permissionDetailList:
        type: array
        items:
          $ref: "./PermissionDetail.yaml#/definitions/permissionDetail"
        description: Permission details
