swagger: "2.0"
definitions:
  sendOutSiteNotice:
    x-jdcloud-module: iam
    required:
      - pin
      - notifyBusinessTypeEnum
      - templateId
      - templateParam
      - smsMessageSource
    properties:
      pin:
        type: string
        description: User pin
      emailSubject:
        type: string
        description: Email subject
      emailContent:
        type: string
        description: Email content
      notifyBusinessTypeEnum:
        type: string
        description: Message type
      templateId:
        type: integer
        description: Template code
      templateParam:
        type: array
        items:
          type: string
        description: Template parameter
      smsMessageSource:
        type: string
        description: Business code (and product application)