swagger: "2.0"
definitions:
  sendSingleMsg:
    x-jdcloud-module: iam
    required:
      - templateId
      - templateParam
      - smsMessageSource
      - pin
      - mobileNum
    properties:
      templateId:
        type: integer
        description: Template code
      templateParam:
        type: array
        items:
          type: string
        description: Template parameter
      smsMessageSource:
        type: string
        description: Business code (and product application)
      pin:
        type: string
        description: User pin
      mobileNum:
        type: string
        description: Mobile number