swagger: "2.0"
definitions:
  userReqVo:
    x-jdcloud-module: iam
    properties:
      pin:
        type: string
        description: User pin
      cscPhone:
        type: string
        description: User’s mobile number
      cscEmail:
        type: string
        description: User’s Email
      name:
        type: string
        description: User name
      userType:
        type: integer
        description: User type
      companyName:
        type: string
        description: Company name
      createTimeStart:
        type: string
        format: date-time
        description: Start time
      createTimeEnd:
        type: string
        format: date-time
        description: End time
      arrearageStatus:
        type: integer
        description: Arrearage status
      groups:
        type: string
        description: User groups, separated with commas: 1-Natural Traffic, 2-Internal Test, 3-Internal key points, 4-Channel users
      group:
        type: integer
        description: User groups: 1-Natural Traffic, 2-Internal Test, 3-Internal key points, 4-Channel users
      billingWhite:
        type: integer
        description: Billing whit list: 1. In the white list, 2. Not in the white list
      tag:
        type: integer
        description: Channel grade: 1-Normal user, 2-Test user, 4-VIP, 8-Other VIP user, 16boss-Migrated account
      pageSize:
        type: integer
        description: Page size
      currentPage:
        type: integer
        description: Current page
