swagger: "2.0"
definitions:
  dwDatabase:
    x-jdcloud-module: xdata
    title: DwDatabase
    type: object
    required:
      - databaseName
    properties:
      id:
        type: integer
        description: Database id
      userName:
        type: string
        description: User name
      databaseName:
        type: string
        description: Database name
      totalTableQuantity:
        type: integer
        description: Number of summary lists
      createTime:
        type: string
        description: Creation time
      lastUpdateTime:
        type: string
        description: Last update time
      physicalStorageCapacity:
        type: string
        description: Last update time
      category:
        type: string
        description: Category
      source:
        type: string
        description: Source
      owner:
        type: string
        description: Owner
      location:
        type: string
        description: Location
      comments:
        type: string
        description: Description information