swagger: "2.0"
definitions:
  azSaleStatusVo:
    x-jdcloud-module: iam
    properties:
      az:
        type: string
        description:
      canSale:
        type: integer
        description: Sold out or not (0-No, 1-Yes)
      visible:
        type: integer
        description: Visible or not (1-Yes, 0-No)