swagger: "2.0"
definitions:
  Flavor:
    x-jdcloud-module: mongodb
    title: Flavor
    type: object
    properties:
      cpu:
        type: integer
        description: Number of CPU Cores
      memory:
        type: integer
        description: Memory, in GB
      iops:
        type: integer
        description: iops
      maxLink:
        type: integer
        description: Maximum Connections
      maxDisk:
        type: integer
        description: Maximum Number of Disks, in GB
      minDisk:
        type: integer
        description: Minimum Number of Disks, in GB
      diskStep:
        type: integer
        description: Disk Step Size
      