swagger: "2.0"
info:
  description: Customized metric monitoring items APIs, providing customized monitoring data reporting function
  title: Monitor Item Customized Monitoring APIs
  version: "v1"
consumes:
- application/json
produces:
- application/json
############################Customized metric monitoring API, reporting service corresponding to cm-put data##############################
###########################Internal domain name: cm-put.openapi.cn-north-1.jdcloud.com Gateway address: monitor.cn-north-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-south-1.jdcloud.com Gateway address: monitor.cn-south-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-east-1.jdcloud.com Gateway address: monitor.cn-east-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-east-2.jdcloud.com Gateway address: monitor.cn-east-2.jdcloud-api.com##############################
paths:
  /customMetrics:
    ###################### Report customized metric monitoring data of user ######################
    post:
      description: The API is for reporting the customized monitoring data, facilitating the user to report the collected time series data to the Cloud Monitor. Original data and aggregated statistical data can be reported in batches. A single request contains up to 50 data points; the data size does not exceed 256k.
      summary: Report monitoring data of user
      operationId: putMetricData
      x-jdcloud-internal: false
      parameters:
      - name: metricDataList
        in: body
        description: "Data parameter"
        schema:
          type: array
          items:
            $ref: "../model/MetricDataCm.yaml#/definitions/metricDataCm"
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: Request ID
              error:
                type: object
                description: Error information
                items:
                  $ref: '../model/ErrorCm.yaml#/definitions/error'
              result:
                properties:
                  success:
                    type: boolean
                    description: All successful write-ins are true, otherwise are false
                  errMetricDataList:
                    type: array
                    items:
                      $ref: '../model/ErrMetricDataCm.yaml#/definitions/metricDataList'
        400:
          description: "invalid parameter"
        429:
          description: "quota exceed"
        500:
          description: "internal server error"