swagger: "2.0"
info:
  description: Customized metric monitoring items APIs, providing customized monitoring data reporting function
  title: Monitor Item Customized Monitoring APIs
  version: "v1"
consumes:
- application/json
produces:
- application/json
############################Customized metric monitoring interface, reporting service corresponding to cm-put data##############################
###########################Internal domain name: cm-put.openapi.cn-north-1.jdcloud.com Gateway address: monitor.cn-north-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-south-1.jdcloud.com Gateway address: monitor.cn-south-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-east-1.jdcloud.com Gateway address: monitor.cn-east-1.jdcloud-api.com##############################
###########################Internal domain name: cm-put.openapi.cn-east-2.jdcloud.com Gateway address: monitor.cn-east-2.jdcloud-api.com##############################
paths:
  /customMetrics:
    ###################### Report customized metric monitoring data of user ######################
    post:
      description: The interface is the interface for customized metric monitoring data reporting, which is convenient for you to report the time series data collected by yourself to the Cloud Monitor. It can report original data and aggregated statistical data. It supports reporting methods in batches. A single request contains up to 50 data points; the data size does not exceed 256k.
      summary: Report monitoring data of user
      operationId: putMetricData
      x-jdcloud-internal: false
      parameters:
      - name: metricDataList
        in: body
        description: "Data parameter"
        schema:
          type: array
          items:
            $ref: "../model/MetricDataCm.yaml#/definitions/metricDataCm"
      responses:
        200:
          description:  OK
          schema:
            properties:
              requestId:
                type: string
                description: Requested identifier id
              error:
                type: object
                description: Error information
                items:
                  $ref: '../model/ErrorCm.yaml#/definitions/error'
              result:
                properties:
                  success:
                    type: boolean
                    description: All successful write-ins are true, or false
                  errMetricDataList:
                    type: array
                    items:
                      $ref: '../model/ErrMetricDataCm.yaml#/definitions/metricDataList'
        400:
          description: "invalid parameter"
        429:
          description: "quota exceed"
        500:
          description: "internal server error"