swagger: "2.0"                                  # Implemented based on Swagger version 2.0
info:
  version: "v1"                                 # OpenApi version number
  title: Cloud Storage APIs
  description: "Cloud storage APIs, mainly Include query Bucket list, create Bucket, delete Bucket and query whether Bucket exists or not. For more APIs, see: https://www.jdcloud.com/help/detail/1901/isCatalog/1"
host: "oss.jdcloud-api.com"                   # Use business line name as the secondary domain name
x-jdcloud-version: "v1"
x-jdcloud-revision: 0.2.4  #It is required to be consistent with ChangeLog