swagger: "2.0"
definitions:
  diskAttachment:
    x-jdcloud-module: disk
    type: object
    properties:
      attachmentId:
        type: string
        description: Attach ID
      diskId:
        type: string
        description: Cloud Disk Service ID
      instanceType:
        type: string
        enum:
          - "vm"
          - "nc"
        description: Type of the instance  attached, vm or nc
      instanceId:
        type: string
        description: ID of instance attached
      status:
        type: string
        description: Attaching state, "attaching", "attached", "detaching" or "detached"
      attachTime:
        type: string
        format: date-time
        description: Attaching Time
