swagger: "2.0"
definitions:
  disk:
    x-jdcloud-module: disk
    type: object
    description: "Cloud Disk Service Information Details"
    properties:
      diskId:
        type: string
        description: Cloud Disk Service ID
      az:
        type: string
        description: AZ, to which the cloud disk service belongs
      name:
        type: string
        description: Name of the cloud disk service. Only Chinese, numbers, uppercase and lowercase letters, English underline "_" and line-through "-" are allowed. It is not allowed to be blank and shall not exceed 32 characters.
      description:
        type: string
        description: Description of the cloud disk service. It allows you to enter all characters under UTF-8 encoding, but no more than 256 characters.
      diskType:
        type: string
        description: Disk type, ssd or premium-hdd
      diskSizeGB:
        type: integer
        description: Disk size, in GiB
      status:
        type: string
        description: Status of the cloud disk service, creating, available, in-use, extending, restoring, deleting, deleted, error_create, error_delete, error_restore or error_extend
      attachments:
        type: array
        items:
          $ref: "./DiskAttachment.yaml#/definitions/diskAttachment"
        description: Attach Information
      snapshotId:
        type: string
        description: Snapshot ID used to create the cloud disk service
      multiAttachable:
        type: boolean
        description: Does the cloud disk support multiple attachments?
      createTime:
        type: string
        format: date-time
        description: Cloud disk service creating time
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: Configuration information for cloud disk service billing
      tags:
        type: array
        items:
          $ref: "./Tag.yaml#/definitions/tag"
        description: Tag information
