swagger: "2.0"
definitions:
  soldout:
    x-jdcloud-module: disk 
    required:
      - AzName 
      - MediaType
      - IsSoldOut
    properties:
      AzName:
        type: string
        description: Availability Zone, to which the Cloud Disk belongs
      MediaType:
        type: string
        enum:
          - "ssd"
          - "premium-hdd"
        description: Type of the Cloud Disk, value ssd or premium-hdd
      IsSoldOut:
        type: boolean 
        description: Is it sold out?
