swagger: '2.0'
info:
  version: v1
  title: storage APIs
  description: Information APIs related to stream computing storage
basePath: '/regions/{regionId}'
paths:
#######Create or update storage################
  /storage:
    post:
      description: Create or update storage
      operationId: addOrUpdateStorage
      parameters:
        - name: storageStr
          in: body
          description: Details of creating or updating storage
          required: true
          schema:
            $ref: "../model/storageInfo.yaml#/definitions/storage"
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  message:
                    type: string
                  status:
                    type: boolean
              requestId:
                type: string
        '400':
          description: UNAUTHENTICATED
        '404':
          description: NOT_FOUND
        '500':
          description: INTERNAL_ERROR
#######Delete the assigned input################
    delete:
      description: Delete the assigned input
      operationId: deleteStorage
      parameters:
        - name: storageId
          in: query
          description: storageId
          required: true
          type: integer  
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  message:
                    type: string
              requestId:
                type: string
        '401':
          description: UNAUTHENTICATED
        '500':
          description: internal error
#######Delete the assigned input################
    get:
      description: Query the assigned input
      operationId: describeStorage
      parameters:
        - name: storageId
          in: query
          description: storageId
          required: true
          type: integer  
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  data:
                    type: object
                    $ref: "../model/storageInfo.yaml#/definitions/storage"
              requestId:
                type: string
        '401':
          description: UNAUTHENTICATED
        '500':
          description: internal error
#######View all the input under the assigned applications################
  /storageList:
    get:
      description: Create or update storage
      operationId: getStorageList
      parameters:
        - name: storageType
          in: query
          description: storage type
          required: true
          type: string
        - name: namespaceId
          in: query
          description: namespaceId
          required: true
          type: string  
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  storageList:
                    type: array
                    items:
                      type: object
                      $ref: "../model/storageInfo.yaml#/definitions/storage"
              requestId:
                type: string
        '401':
          description: UNAUTHENTICATED
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
