swagger: "2.0"
info:
  version: "v1"
  title: Starting Template
  description: interface related to starting template

basePath: /regions/{regionId}

paths:
  "/instanceTemplates":
    ###################### Create Starting Template Interface ######################
    post:
      description: |
        Create a start-up template for a specified parameter. The starting template contains most of the configuration parameters when creating a virtual machine,  avoiding repetitive work when creating a virtual machine each time. <br>
        If you create a virtual machine using the starting template,  if you specify that certain parameters conflict with the parameters in the template,  then the newly specified parameters replace the parameters in the template. <br>
        If you create a virtual machine using the starting template,  the database Disks parameter in the template will fail if it is specified that the image ID is not consistent with the image ID in the template. <br>
        If you create a virtual machine with availability group (Ag),  the parameters in the template associated with Ag are not adjustable,  and only the template should prevail.
      operationId: createInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: instanceTemplateData
          in: body
          required: true
          description: starting template data
          schema:
            $ref: "../model/InstanceTemplateSpec.yaml#/definitions/instanceTemplateSpec"
        - name: name
          in: query
          type: string
          required: true
          Description: The name of the starting template,  <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
        - name: description
          in: query
          type: string
          Description: Start the description of the template,  <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplateId:
                    type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Starting Template List Interface ######################
    get:
      description: |
        Query start template list
      operationId: describeInstanceTemplates
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "Page; Default is 1"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "Page size; Default is 20;Range of value[10, 100] "
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            name-Starting template name,  fuzzy match,  support multiple
            instanceTemplateId-Start template ID,  match exactly,  support multiple
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplates:
                    type: array
                    items:
                      $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
                  totalCount:
                    type: number
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/instanceTemplates/{instanceTemplateId}":
    ######################Starting Template Detail Interface ######################
    get:
      description: |
        Query start template details
      operationId: describeInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ######################Delete Starting Template Interface ######################
    delete:
      description: |
        Delete a StartingTemplate
      operationId: deleteInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ######################Modify Starting Template Information Interface ######################
    patch:
      description: |
        Modify information for a starting template,  including name,  description
      operationId: updateInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: description
          in: query
          type: string
          Description: template description,  <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
        - name: name
          in: query
          type: string
          Description: template name, <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">Refer to the public parameter specification</a>.
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


  "/instanceTemplates/{instanceTemplateId}:verify":
    ###################### Verify that the starting template is available ######################
    get:
      description: |
        Verify the effectiveness of the starting template
      operationId: verifyInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


# path general parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Geo ID
  instanceTemplate:
    name: instanceTemplateId
    in: path
    required: true
    type: string
    description: starting template ID
