swagger: "2.0"
info:
  version: "v1"
  title: SSH Key pair
  description: related interface on SSH key pair

basePath: /regions/{regionId}

paths:
  "/keypairs":
    ###################### Create ssh key pair ######################
    post:
      description: |
        Create ssh key pair. The public key section is stored in JD Cloud and returned to the PKCS # 8 format private key that is not encrypted. You have only one opportunity to save your private key. Please keep it properly. <br>
        An error is returned if the key pair name already exists.
      operationId: createKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          type: string
          in: query
          required: true
          description: |
            The key pair name needs to be globally unique. <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: key pair name
                  privateKey:
                    type: string
                    Description: The private key part of the key pair,  the PEM PKCS # 8 format.
                  keyFingerprint:
                    type: string
                    Description: The fingerprint of the key pair,  based on the public key fingerprint format defined in RFC4716,  uses the MD5 information digest algorithm.
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Querying ssh Key Pair List ######################
    get:
      description: |
        批量查询密钥对。<br>
        This interface supports paging query by default of 20 pages per page.
      operationId: describeKeypairs
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: page; Default is 1
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: page size;Default is 20;Range of value[10, 100]
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            TagNames-Key pair name,  exact match,  support multiple
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  keypairs:
                    type: array
                    items:
                      $ref: "../model/Keypair.yaml#/definitions/keypair"
                  totalCount:
                    type: number
                    Description: Total data number
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs:import":
    ###################### Import ssh Key Pairs ######################
    post:
      description: |
        Import the public key part of the key pair generated by other tools. <br>
        An error is returned if the key pair name already exists.
      operationId: importKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          in: query
          type: string
          required: true
          description: |
            The key pair name needs to be globally unique. <a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification </a>.
        - name: publicKey
          in: query
          type: string
          required: true
          description: public key part of key pair
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: key pair name
                  keyFingerprint:
                    type: string
                    Description: The fingerprint of the key pair,  based on the public key fingerprint format defined in RFC4716,  uses the MD5 information digest algorithm.
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs/{keyName}":
    ###################### Delete ssh Key Pair ######################
    delete:
      description: |
        Remove ssh key pair.
      operationId: deleteKeypair
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# path general parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Geo ID
  keyName:
    name: keyName
    in: path
    required: true
    type: string
    description: key pair name
