swagger: "2.0"
info:
  version: "v1"
  title: Quota
  description: interface related to quota

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### Search Quota ######################
    get:
      description: |
        Query Quota,  Support: virtual machine,  Image,  key pair,  Template
      operationId: describeQuotas
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            resource Types-A resource type that supports multiple [instance,  keyair,  image,  instanceTemplate]
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quotas:
                    type: array
                    description: quota list
                    items:
                      $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### Modify Quota ######################
    patch:
      description: |
        modify quotas,  this interface is an internal interface,  support: virtual machine,  image,  key pair,  template
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          description: source type [instance, keypair, image, instanceTemplate]
        - name: limit
          in: query
          type: integer
          description: upper quota limit
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

# path general parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Geo ID