swagger: "2.0"
definitions:
  target:
    x-jdcloud-module: streambus
    title: target
    type: object
    properties:
      name:
        type: string
        description: "Destination of archiving"
      recordSize: 
        type: integer
        description: "It starts to archive when achieving the data bulk"
      cycle:
        type: integer
        description: "Time period of performing archiving task"