swagger: "2.0"
definitions:
  imageConstraint:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: image ID
      imageInstanceTypeConstraint:
        description: image specification type limit
        $ref: "#/definitions/imageInstanceTypeConstraint"
  imageInstanceTypeConstraint:
    x-jdcloud-module: vm
    properties:
      constraintsType:
        description: "restricted specification type. excludes: exclude specified instance types; includes: only the specified instance type is included,  which is not supported temporarily"
        type: string
      instanceTypes:
        description: specification type list
        type: array
        items:
          type: string
