swagger: "2.0"
definitions:
  imageConstraint:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: Image ID
      imageInstanceTypeConstraint:
        description: Specification limit for instance type created by image
        $ref: "#/definitions/imageInstanceTypeConstraint"
  imageInstanceTypeConstraint:
    x-jdcloud-module: vm
    properties:
      constraintsType:
        description: Restricted specification type. excludes: instance types not supported; includes: instance types supported.
        type: string
      instanceTypes:
        description: Instance type list
        type: array
        items:
          type: string
