swagger: "2.0"
definitions:
  image:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: image ID
      name:
        type: string
        description: image name
      platform:
        type: string
        description: OS Release,  [suse,  debian,  ubuntu,  centos,  windows-server]
      osVersion:
        type: string
        description: OS version number
      architecture:
        type: string
        Description: image Architecture i386,  x86 _ 64
      systemDiskSizeGB:
        type: integer
        description: image system disk size
      imageSource:
        type: string
        description: image source,  jcloud: public image,  marketplace: image marketplace,  image self: user's own image share: image shared by other users
      osType:
        type: string
        description: the operating system type of the image,  [windows,  linux]
      status:
        type: string
        description: <a href="https://www.jdcloud.com/help/detail/3871/isCatalog/1">参考镜像状态</a>
      createTime:
        type: string
        format: date-time
        description: creation time
      sizeMB:
        type: integer
        description: image itself size
      desc:
        type: string
        description: image description
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: system disk configuration
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: package image data disk mapping information
      snapshotId:
        type: string
        Description: The cloud disk service drives the snapshot id of the system disk,  and when the virtual machine is created,  the system disk is created by default using this snapshot
      rootDeviceType:
        type: string
        Description: The system disk type supported by the image. localDisk: Support system disk for this site.cloudDisk: Support cloud disk system disk
      progress:
        type: string
        description: progress in image replication,  in percentage,  for example: 80
