swagger: "2.0"
definitions:
  instanceTemplateSpec:
    x-jdcloud-module: vm
    required:
      - instanceType
      - imageId
      - primaryNetworkInterface
      - systemDisk
    properties:
      instanceType:
        type: string
        Description: spec type,  query<a href="https://www.jdcloud.com/help/detail/2901/isCatalog/1">DescribeInstanceTypes</a> Interface gives specification information for the specified zone or availability zone.
      imageId:
        type: string
        Description: image ID,  query <a href="https://www.jdcloud.com/help/detail/2874/isCatalog/1">DescribeImages</a> Interface gets the image information for the specified zone.
      password:
        type: string
        Description: password,  <a href = "https://www.jdcloud.com/help/detail/3870/isCatalog/1 "> Refer to the public parameter specification</a>.
      keyNames:
        type: array
        items:
          type: string
        description: the key pair name; only one is currently supported
      elasticIp:
        $ref: "./InstanceTemplateElasticIpSpec.yaml#/definitions/instanceTemplateElasticIpSpec"
        description: EIP specification associated with the primary IP of the primary network card
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: primary network card configuration information
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: system disk configuration information
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachmentSpec.yaml#/definitions/instanceTemplateDiskAttachmentSpec"
        description: data disk configuration information