swagger: "2.0"
definitions:
  instanceTemplateData:
    x-jdcloud-module: vm
    properties:
      instanceType:
        type: string
        description: specification type
      vpcId:
        type: string
        description: ID of the VPC to which the machine network card belongs
      imageId:
        type: string
        description: image ID
      includePassword:
        type: boolean
        description: whether the starting template contains a custom password,  true: password contained,  false: password not contained
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        description: system disk information
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        Description: The data disk information. The virtual machine of the system disk can be attached with eight data disks. The virtual machine of the cloud disk service (cloud type) can attach 7 data disks.
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: primary network card information
      elasticIp:
        $ref: "./InstanceTemplateElasticIp.yaml#/definitions/instanceTemplateElasticIp"
        description: EIP specification associated with the primary IP of the primary network card
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: the key pair name; only one is currently supported