swagger: "2.0"
definitions:
  instanceDiskAttachment:
    x-jdcloud-module: vm
    type: object
    properties:
      diskCategory:
        type: string
        description: |
          Disk classification, the local disk or data disk is taken.
          The system disk supports local disk or cloud disk. The system disk selects local Type, and the user must use the image localDisk type; If the system disk selects the cloud type, the user must use the image of the cloudDisk type.
          The data disk supports cloud disk only.
      autoDelete:
        type: boolean
        description: |
          Deleting this disk with the VM automatically when the machine is deleted. The default value is true, which cannot be changed by local.
          This parameter does not take effect if the data disk in the VM is a monthly package.
          This parameter does not take effect if the data disk in the VM is a shared data disk.
      localDisk:
        $ref: "./LocalDisk.yaml#/definitions/localDisk"
        description: Local disk instance type
      cloudDisk:
        $ref: "../../disk/model/Disk.yaml#/definitions/disk"
        description: Cloud disk service instance type
      deviceName:
        type: string
        description: Data disk logical attach point, value range: vda, vdb, vdc, vdd, vde, vdb, vdg, vdh, vdi
