swagger: "2.0"
definitions:
  instanceSpec:
    x-jdcloud-module: vm
    required:
      - name
    properties:
      agId:
        type: string
        Description: availability group Id. Once this parameter is specified,  the virtual machine can only be created by the instance template associated with the availability group,  and the parameters in the instance template cannot be replaced. Parameters other than instance templates can also be specified.
      instanceTemplateId:
        type: string
        Description: Instance template id. If you do not use an availability group,  there is no information in the instance template,  you need to use the parameters that create the virtual machine,  or choose to replace the parameters in the starting template.
      az:
        type: string
        Description: The availability zone to which the virtual machine belongs.
      instanceType:
        type: string
        Description: Specification type. Can query <a href = "https://www.jdcloud.com/help/detail/2901/isCatalog/1"> DescribeInstanceTypes</a> interface gives specification information for the specified zone or availability zone.
      imageId:
        type: string
        description: image ID. Can query <a href = "https://www.jdcloud.com/help/detail/2874/isCatalog/1"> DescribeImages</a> interface gets the image information for the specified zone.
      name:
        type: string
        Description: virtual machine name,  <a href ="https://www.jdcloud.com/help/detail/3870/isCatalog/1"> Refer to the public parameter specification</a>.
      password:
        type: string
        Description: password,  <a href = "https://www.jdcloud.com/help/detail/3870/isCatalog/1 "> Refer to the public parameter specification</a>.
      keyNames:
        type: array
        items:
          type: string
        Description: The key pair name currently only supports incoming one.
      elasticIp:
        $ref: "../../vpc/model/ElasticIpSpec.yaml#/definitions/elasticIpSpec"
        description: EIP specification associated with the primary IP of the primary network card
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceNetworkInterfaceAttachmentSpec"
        description: primary network card configuration information
      systemDisk:
        $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        description: system disk configuration information
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        Description: The configuration information of the data disk. The virtual machine of the system disk of local disk (or type) can attach the 8 data disks,  and the virtual machine of the cloud disk service (cloud type) as the system disk can attach the 7 data disks.
      charge:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: |
          Billing configuration
          The virtual machine does not support paying by consumption. The default is to paid by configuration.
          In the case of packaging a data disk,  the billing method of the data disk can only be consistent with the virtual machine.
          In the case of packaging EIP,  if the billing method of the public IP is not specified to be paid by consumption,  the IP billing mode of the public network can only be consistent with the virtual machine.
      description:
        type: string
        Description: machine description,  <a href = "https://www.jdcloud.com/help/detail/3870/isCatalog/1 "> Refer to the public parameter specification</a>.
