swagger: "2.0"
definitions:
  instanceNetworkInterface:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: ENI ID
      macAddress:
        type: string
        description: Ethernet address
      vpcId:
        type: string
        description: Virtual Network ID
      subnetId:
        type: string
        description: Subnet ID
      securityGroups:
        type: array
        items:
          $ref: "./SecurityGroupSimple.yaml#/definitions/securityGroupSimple"
          description: List of security groups
      sanityCheck:
        type: integer
        description: Source and destination IP address verification with a value of 0 or 1
      primaryIp:
        $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: Network interface primary IP
      secondaryIps:
        type: array
        description: Network interface secondary IP
        items:
          $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
