swagger: "2.0"
definitions:
  instanceTemplateNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    required:
      - networkInterface
    properties:
      deviceIndex:
        type: integer
        description: device Index; The index of the primary network card must be 1; The primary network card is currently only supported
      autoDelete:
        type: boolean
        Description: Indicates whether the network card is deleted when deleting an instance,  and the default is true; currently can only be true
      networkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceSpec.yaml#/definitions/instanceTemplateNetworkInterfaceSpec"
        description: network card interface specification;This field is currently required