swagger: "2.0"
definitions:
  instanceTemplateDiskAttachmentSpec:
    x-jdcloud-module: vm
    properties:
      diskCategory:
        type: string
        description: |
          Disk classification, the local disk or data disk is taken.
          The system disk supports local disk or cloud disk. The system disk selects local Type, and the user must use the image localDisk type; If the system disk selects the cloud type, the user must use the image of the cloudDisk type.
          The data disk supports cloud disk only.
      autoDelete:
        type: boolean
        description: |
          Deleting this disk with the VM automatically when the machine is deleted. The default value is true, which cannot be changed by local.
          This parameter does not take effect if the data disk in the VM is a monthly package.
          This parameter does not take effect if the data disk in the VM is a shared data disk.
      cloudDiskSpec:
        $ref: "./InstanceTemplateDiskSpec.yaml#/definitions/instanceTemplateDiskSpec"
        description: Data disk instance type
      deviceName:
        type: string
        description: Data disk logical attach point, value range: vda, vdb, vdc, vdd, vde, vdb, vdg, vdh, vdi
      noDevice:
        type: boolean
        description: |
          Excludes the device and parameter noDevice is used with deviceName.
          Create a template: deviceName: vdb, noDevice: true, the data disk vdb in the image is not involved in creating the machine.
