swagger: "2.0"
definitions:
  instanceDiskAttachmentSpec:
    x-jdcloud-module: vm
    properties:
      diskCategory:
        type: string
        description: |
          Disk classification,  taking the value as the local or cloud data disk.
          The system disk supports local disk (local) or cloud disk service (cloud). The system disk selects image Type,  and you must use the image localDisk type; If the system disk selects the cloud type,  you must use the image of the cloudDisk type.
          The data disk supports only cloud disk service (cloud).
      autoDelete:
        type: boolean
        description: |
          Deleting this disk with the virtual machine automatically deletes the disk when the machine is deleted. If the default value is true,  this value cannot be changed.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a monthly package.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a shared type data disk.
      cloudDiskSpec:
        $ref: "../../disk/model/DiskSpec.yaml#/definitions/diskSpec"
        description: data disk configuration
      deviceName:
        type: string
        description: data disk logical attach point,  range of values: vda,  vdb,  vdc,  vdd,  vde,  vdb,  vdg,  vdh,  vdi
      noDevice:
        type: boolean
        description: |
          Excludes the device and uses this parameter noDevice to work with deviceName.
          Create a package image: if deviceName: vdb,  noDevice: true,  the data disk vdb in the virtual machine does not participate in the creation of an image.
          Create a template: if deviceName: vdb,  noDevice: true,  the data disk vdb in the image does not participate in the creation of the machine.
          Create a machine: if deviceName: vdb,  noDevice: true,  the data disk vdb in the image or the data disk vdb in the template (using the template creation machine) does not participate in the creation of the machine.
