swagger: "2.0"
definitions:
  instanceDiskAttachment:
    x-jdcloud-module: vm
    type: object
    properties:
      diskCategory:
        type: string
        description: |
          Disk classification,  taking the value as the local or cloud data disk.
          The system disk supports local disk (local) or cloud disk service (cloud). The system disk selects image Type,  and you must use the image localDisk type; If the system disk selects the cloud type,  you must use the image of the cloudDisk type.
          The data disk supports only cloud disk service (cloud).
      autoDelete:
        type: boolean
        description: |
          Deleting this disk with the virtual machine automatically deletes the disk when the machine is deleted. If the default value is true,  this value cannot be changed.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a monthly package.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a shared type data disk.
      localDisk:
        $ref: "./LocalDisk.yaml#/definitions/localDisk"
        description: local disk configuration
      cloudDisk:
        $ref: "../../disk/model/Disk.yaml#/definitions/disk"
        description: cloud disk service configuration
      deviceName:
        type: string
        description: "data disk logical attach point,  range of values: vda,  vdb,  vdc,  vdd,  vde,  vdb,  vdg,  vdh,  vdi"
