swagger: "2.0"
definitions:
  instance:
    x-jdcloud-module: vm
    title: Instance
    type: object
    properties:
      instanceId:
        type: string
        description: virtual machine ID
      instanceName:
        type: string
        description: virtual machine name
      instanceType:
        type: string
        description: virtual machine type
      vpcId:
        type: string
        description: ID of the VPC to which the machine network card belongs
      subnetId:
        type: string
        description: ID of the subnet to which the machine network card belongs
      privateIpAddress:
        type: string
        description: primary network card primary IP address
      elasticIpId:
        type: string
        description: The ID of the primary network card primary IP associating EIP
      elasticIpAddress:
        type: string
        description: the address of the primary network card primary IP associating EIP
      status:
        type: string
        description: virtual machine status,<a href="https://www.jdcloud.com/help/detail/3869/isCatalog/1">Refer to the virtual machine status</a>
      description:
        type: string
        description: virtual machine description
      imageId:
        type: string
        description: image ID
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: system disk configuration
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: data disk configuration
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: primary network card configuration
      secondaryNetworkInterfaces:
        type: array
        items:
          $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: secondary network card configuration
      launchTime:
        type: string
        format: date-time
        description: creation time
      az:
        type: string
        description: the availability zone of the virtual machine
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: key pair name
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: billing information
      ag:
        $ref: "./Ag.yaml#/definitions/ag"
        description: availability group,  where a highly available group is used to create a virtual machine,  a highly available group name can be displayed here
      faultDomain:
        type: string
        description: error domains in availability groups
      tags:
        type: array
        items:
          $ref: "./Tag.yaml#/definitions/tag"
        description: Tag information
