swagger: "2.0"
definitions:
  instanceDiskAttribute:
    x-jdcloud-module: vm
    properties:
      diskId:
        type: string
        description: cloud disk service ID
      autoDelete:
        type: boolean
        description: |
          Deleting this disk with the virtual machine automatically deletes the disk when the machine is deleted. If the default value is false,  this value cannot be changed.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a monthly package.
          This parameter does not take effect if the data disk (cloud) in the virtual machine is a shared type data disk.
