swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachment:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: Device Index
      autoDelete:
        type: boolean
        Description: Indicates whether the network card is deleted when deleting an instance,  and the default is true; currently can only be true
      networkInterface:
        $ref: "./InstanceNetworkInterface.yaml#/definitions/instanceNetworkInterface"
        description: network card interface specification
