swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachmentSpec:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: Network card device Index,  and the network card can only be 1
      networkInterface:
        $ref: "../../vpc/model/NetworkInterfaceSpec.yaml#/definitions/networkInterfaceSpec"
        description: network card interface specification
