swagger: "2.0"
definitions:
  instanceType:
    x-jdcloud-module: vm
    properties:
      family:
        type: string
        description: instance
      instanceType:
        type: string
        description: specification type,  such as g.b1. 2xlge
      cpu:
        type: integer
        description: cpu number
      memoryMB:
        type: integer
        description: memory size
      nicLimit:
        type: integer
        description: number of elastic network interface supported
      desc:
        type: string
        description: description
      state:
        type: array
        items:
          $ref: "./InstanceTypeState.yaml#/definitions/instanceTypeState"
        description: specification status