swagger: "2.0"
definitions:
  instanceTemplateElasticIpSpec:
    x-jdcloud-module: vm
    required:
      - bandwidthMbps
      - chargeMode
    properties:
      bandwidthMbps:
        type: integer
        description: speed limit for EIP (unit: MB)
      provider:
        type: string
        enum:
          - "BGP"
          - "nonBGP"
        description: IP service provider takes the value of BGP,  nonBGP
      chargeMode:
        type: string
        enum:
          - "bandwith"
          - "flow"
        description: billing type,  supporting billing by bandwidth,  billing by flow