swagger: "2.0"
definitions:
  instanceTemplate:
    x-jdcloud-module: vm
    properties:
      id:
        type: string
        description: starting template ID
      name:
        type: string
        description: starting template name
      description:
        type: string
        description: starting template description
      instanceTemplateData:
        $ref: "./InstanceTemplateData.yaml#/definitions/instanceTemplateData"
        description: starting template data
      ags:
        type: array
        items:
          $ref: "./Ag.yaml#/definitions/ag"
        description: availability group (ag) information associated
      createdTime:
        type: string
        format: date-time
        description: creation time