swagger: "2.0"
definitions:
  instanceNetworkAttribute:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: Elastic Network Card ID
      autoDelete:
        type: boolean
        Description: Auto-delete with the host,  if default is False.
