swagger: "2.0"
definitions:
  instancePrivateIpAddress:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: virtual machine ID
      privateIpAddress:
        type: string
        description: The intranet primary IP address in the primary network