swagger: "2.0"
definitions:
  keypair:
    x-jdcloud-module: vm
    properties:
      keyName:
        type: string
        description: key pair name
      keyFingerprint:
        type: string
        Description: The fingerprint of the key pair,  based on the public key fingerprint format defined in RFC4716,  uses the MD5 information digest algorithm.