swagger: "2.0"
definitions:
  localDisk:
    x-jdcloud-module: vm
    description: describes the local disk of an instance
    type: object
    properties:
      diskType:
        type: string
        description: disk type,  value range {premium-hdd,  ssd}
      diskSizeGB:
        type: integer
        description: disk size
