swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: vm
    properties:
      resourceType:
        type: string
        description: source type [instance, keypair, image, instanceTemplate]
      limit:
        type: integer
        description: upper quota limit
      used:
        type: integer
        description: used quota
