swagger: "2.0"
definitions:
  securityGroupSimple:
    x-jdcloud-module: vm
    description: Describes the security group for instance associated
    type: object
    properties:
      groupId:
        type: string
        description: security groupID
      groupName:
        type: string
        description: security group name
