swagger: "2.0"
definitions:
  tag:
    x-jdcloud-module: vm
    properties:
      key:
        type: string
        description: Tag key
      value:
        type: string
        description: Tag value
