swagger: "2.0"
definitions:
  cluster:
    x-jdcloud-module: jmr
    title: cluster
    type: object
    properties:
      clusterId:
        type: string
        description: Cluster Id
      type:
        type: integer
        description: |
                  "Required parameters, billing type:"
                  "Pay by configuration<br/>"
                       "601-609: Monthly package for 1 month to 9 months"
                       "610: Monthly package for 1 year"
                       "620: Monthly package for 2 years"