swagger: "2.0"
definitions:
  cronJobData:
    x-jdcloud-module: jmr
    title: cronJobData
    type: object
    properties:
      totalNum:
        type: integer
        description: Cluster job number
      cronJobs:
        type: array
        items:
          $ref: "../model/JmrPlanViewModel.yaml#/definitions/jmrPlanViewModel"