swagger: "2.0"
definitions:
  hardwareInfo:
    x-jdcloud-module: jmr
    title: hardwareInfo
    type: object
    properties:
      nodeName:
        type: string
        description: Node name
      nodeType:
        type: string
        description: Node type
      nodeStatus:
        type: string
        description: Node status
      innerIp:
        type: string
        description: Private IP
      outerIp:
        type: string
        description: Internet IP
      firewall:
        type: string
        description: Firewall
      nodeCoreNum:
        type: integer
        description: Node core number
      nodeMemoryNum:
        type: integer
        description: Node memory
      nodeSystemInfo:
        type: string
        description: Node system information
      nodeDiskType:
        type: string
        description: Node hard disk type
      nodeDiskVolume:
        type: integer
        description: Node hard disk capacity
      serverId:
        type: string
        description: Node instance ID
      msg:
        type: string
        description: Message
      instanceType:
        type: string
        description: Node hardware configuration
      instanceInfo:
        type: string
        description: Node hardware type