swagger: "2.0"
definitions:
  idataCluster:
    x-jdcloud-module: jmr
    title: idataCluster
    type: object
    properties:
      id:
        type: string
        description: Cluster id
      name:
        type: string
        description: Cluster name
      status:
        type: string
        description: Cluster status
      createTime:
        type: string
        format: date
        description: Cluster creation time
      duration:
        type: string
        description: Cluster operating hours
      ip:
        type: string
        description: Cluster ip
      port:
        type: string
        description: No. of port providing service
      jdbcUrl:
        type: string
        description: url of jdbc database
      jdbcSpark:
        type: string
        description: Corresponding spark of database
      zepplinUrl:
        type: string
        description: url of zepplin


