swagger: "2.0"
definitions:
  jmrJobViewModel:
    x-jdcloud-module: jmr
    title: jmrJobViewModel
    type: object
    properties:
      id:
        type: integer
        description:
      jobId:
        type: string
        description: Job ID
      jobName:
        type: string
        description: Job name
      jobType:
        type: string
        description: Job type
      jobStatus:
        type: string
        description: Job status
      jobGroup:
        type: string
        description: Job group
      jobTrigger:
        type: string
        description: Job trigger
      cronExpression:
        type: string
        description: Regular task time
      orderBy:
        type: string
        description: Extra field, optional
      isSelfDependence:
        type: integer
      isVirtualTask:
        type: integer
      taskScheduleType:
        type: integer
      retryTimes:
        type: integer
        description: Number of job retry
      isSendMsg:
        type: boolean
        description: Whether to send a SMS notice after job is failed
      userpin:
        type: string
        description: User name
      createTime:
        type: string
        format: date
        description: Creation time
      location:
        type: string
        description: Location
      params:
        type: string
        description: Required parameter
      dataCenter:
        type: string
        description: Date center
      clusterId:
        type: string
        description: Cluster ID
      clusterName:
        type: string
        description: Cluster name
      clusterStatus:
        type: string
        description: Extra field

