swagger: "2.0"
definitions:
  jmrTaskViewModel:
    x-jdcloud-module: jmr
    title: jmrTaskViewModel
    type: object
    properties:
      id:
        type: integer
      taskId:
        type: string
        description: Job Id
      taskName:
        type: string
        description: Job name
      taskType:
        type: string
        description: Job type
      status:
        type: string
        description: Status
      startTime:
        type: string
        format: date
        description: Start time
      endTime:
        type: string
        format: date
        description: End time
      duration:
        type: string
        description: Time of duration
      userpin:
        type: string
        description: User name
      dataCenter:
        type: string
        description: Data center, i.e. regionId
      jobId:
        type: string
      planId:
        type: string
      workflowId:
        type: string
        description: Workflow Id
      workflowInstanceId:
        type: string
        description: Workflow instance Id