swagger: "2.0"
definitions:
  options:
    x-jdcloud-module: jmr
    title: options
    type: object
    properties:
      value:
        type: string
        description: Specification description of the corresponding machine
      label:
        type: string
        description: CPU and memory size of the machine
