swagger: "2.0"
definitions:
  scale:
    x-jdcloud-module: jmr
    title: scale
    type: object
    properties:
      core:
        type: integer
        description: CPU core number
      memory:
        type: integer
        description: Memory size, with the unit of G