swagger: "2.0"
definitions:
  selectParams:
    x-jdcloud-module: jmr
    title: selectParams
    type: object
    properties:
      pageNum:
        type: integer
        description: Search paging number, optional condition
      pageSize:
        type: integer
        description: Search paging size, optional condition
      orderBy:
        type: string
        description: Ranking condition, optional
      status:
        type: string