swagger: "2.0"
definitions:
  softStack:
    x-jdcloud-module: jmr
    title: softStack
    type: object
    properties:
      version:
        type: string
        description: JMR current revision
      software:
        type: string
        description: |
           "Adopted software and revision, such as"
           "HADOOP-2.6.0|HIVE-1.2.1|SPARK-2.0.0|ALLUXIO-1.0.1|ZOOKEEPER-3.4.5|ZEPPELIN-0.6.1"


