swagger: "2.0"
definitions:
  userAccessKey:
    x-jdcloud-module: jmr
    title: userAccessKey
    type: object
    properties:
      id:
        type: integer
        description: User pass id
      pin:
        type: string
        description: User name
      account:
        type: string
        description: User account
      accessKey:
        type: string
        description: Access key, AccessKey is used for calling cloud service API with program method
      accessKeySecret:
        type: string
        description: AccessKeySecret is the key pair used to verify the user
      expire:
        type: string
        format: date
        description: Expiration time
      created:
        type: string
        format: date-time
        description: Creation time
      modified:
        type: string
        format: date-time
        description: Update time
      modifier:
        type: string
        description: Update operator
      state:
        type: integer
        description: Status
      yn:
        type: integer
