swagger: "2.0"
definitions:
  dwHiveObjectPrivileges:
    x-jdcloud-module: xdata
    title: DwHiveObjectPrivileges
    type: object
    properties:
      status:
        type: boolean
        description: Status
      message:
        type: string
        description: Return information
      select:
        type: boolean
        description: select permission
      insert:
        type: boolean
        description: insert permission
      update:
        type: boolean
        description: update permission
      delete:
        type: boolean
        description: delete permission
      drop:
        type: boolean
        description: drop permission
      create:
        type: boolean
        description: create permission
      alter:
        type: boolean
        description: alter permission
      owner:
        type: boolean
        description: Is it the owner or not