swagger: "2.0"
definitions:
  copyImage:
    x-jdcloud-module: vm
    properties:
      destinationImageId:
        type: string
        description: "Target image ID after replication"
      sourceImageId:
        type: string
        description: "Source image ID"