swagger: "2.0"
definitions:
  instanceType:
    x-jdcloud-module: vm
    properties:
      family:
        type: string
        description: "Instance type"
      instanceType:
        type: string
        description: "Instance type, such as g.b1.2xlarge"
      cpu:
        type: integer
        description: "CPU number"
      memoryMB:
        type: integer
        description: "Memory size"
      nicLimit:
        type: integer
        description: "Number of ENI supported"
      desc:
        type: string
        description: "Description"
      state:
        type: array
        items:
          $ref: "./InstanceTypeState.yaml#/definitions/instanceTypeState"
        description: "Instance type status"