swagger: "2.0"
definitions:
  instanceStatus:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: VM ID
      status:
        type: string
        description: <a href="https://www.jdcloud.com/help/detail/3869/isCatalog/1">参考云主机状态</a>